language: clojure
lein: lein2
script:
  - lein2 midje :filters -fullbench
  - lein2 with-profile +1.6 midje :filters -fullbench
  - lein2 with-profile +1.7 midje :filters -fullbench
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
